package com.emilie.serverless.patient.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@DynamoDBTable(tableName = "Utilize DynamoDBMapperConfig")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Patientdetail {
	
	
	private String id;
	private String firstName;
	private String lastName;
	private String emailAddress;
	private String userName;
	
	 @DynamoDBHashKey(attributeName = "id")
	    @DynamoDBAutoGeneratedKey
	    public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	 @DynamoDBAttribute(attributeName = "firstname")
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	 @DynamoDBAttribute(attributeName = "lastname")
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	 @DynamoDBAttribute(attributeName = "emailaddress")
	public String getEmailAddress() {
		return emailAddress;
	}
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}
	 @DynamoDBAttribute(attributeName = "username")
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	
	

}
